# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
sass:
    sass_dir: css/sass
host: 0.0.0.0